---
  hosts: R1
  gather_facts: no

  tasks:
    - name: Set Ethernet0/1 IPv4 address
      ios_l3_interface:
        name: Ethernet0/2
        ipv4: 192.168.12.1/24
    - name: no shut
      ios_interface:
        name: Ethernet0/2
        state: present
        
    - name: Show ip
      ios_command:
        commands:
          - show ip int brief
      register: show_ip

    - debug: var=show_ip.stdout_lines
    
    - name: Set Ethernet0/1 IPv4 address
      ios_l3_interface:
        name: Ethernet0/1
        ipv4: 192.168.1.1/24
    - name: no shut
      ios_interface:
        name: Ethernet0/1
        state: present
        
    - name: Show ip
      ios_command:
        commands:
          - show ip int brief
      register: show_ip

    - debug: var=show_ip.stdout_lines
    
    - name: Set IP
    
  hosts: R2
  gather_facts: no

  tasks:
    - name: Set Ethernet0/1 IPv4 address
      ios_l3_interface:
        name: Ethernet0/2
        ipv4: 192.168.12.2/24
    - name: no shut
      ios_interface:
        name: Ethernet0/2
        state: present
        
    - name: Show ip
      ios_command:
        commands:
          - show ip int brief
      register: show_ip

    - debug: var=show_ip.stdout_lines
    
    - name: Set Ethernet0/1 IPv4 address
      ios_l3_interface:
        name: Ethernet0/1
        ipv4: 192.168.2.1/24
    - name: no shut
      ios_interface:
        name: Ethernet0/1
        state: present
        
    - name: Show ip
      ios_command:
        commands:
          - show ip int brief
      register: show_ip

    - debug: var=show_ip.stdout_lines
